services:
  - type: web
    name: ferraz-conecta
    env: docker
    plan: starter
    region: oregon
    buildCommand: docker build -t ferraz-conecta .
    startCommand: docker run -p $PORT:80 ferraz-conecta
    envVars:
      - key: APP_URL
        value: https://ferraz-conecta.onrender.com
      - key: APP_DEBUG
        value: false
      - key: DB_HOST
        fromDatabase:
          name: ferraz-conecta-db
          property: host
      - key: DB_USERNAME
        fromDatabase:
          name: ferraz-conecta-db
          property: username
      - key: DB_PASSWORD
        fromDatabase:
          name: ferraz-conecta-db
          property: password
      - key: DB_DATABASE
        fromDatabase:
          name: ferraz-conecta-db
          property: database
      - key: DB_PORT
        fromDatabase:
          name: ferraz-conecta-db
          property: port

databases:
  - name: ferraz-conecta-db
    databaseName: ferraz_conecta
    user: ferraz_conecta_user
    plan: starter 